### ISSUE TITLE
Refactor arguments to `pirateship adapter <ssid> [wpa-key]`

### ISSUE THREAD

**Issue by rjcorwin** [ole-vi/pirateship#1]
That would be cool.

**Comment by rjcorwin** [comment]
... or how about `pirateship wifi <ssid> [passphrase]`.

**Comment by treehouse-su** [comment]
maybe 'pirateship wlan0 <ssid> [passphrase]' is better

**Comment by treehouse-su** [comment]
also deprecate 'pirateship adapter ...' command

**Comment by dogi** [comment]
done ;)

**Comment by rjcorwin** [comment]
+1
